# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:48:16+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Book(BaseModel):
    id: Optional[str] = Field(None, examples=['afd6'])
    name: Optional[str] = Field(None, examples=['The Shadow Out of Time'])
    year: Optional[str] = Field(None, examples=['1934'])


class Sentence(BaseModel):
    book: Optional[Book] = None
    id: Optional[str] = Field(None, examples=['d75b3350'])
    sentence: Optional[str] = Field(
        None,
        examples=[
            'Around the first week in July I developed an unaccountable set of mixed emotions about that general northeasterly region.'
        ],
    )


class BooksGetResponse(BaseModel):
    data: Optional[List[Book]] = None


class BooksIdSentencesGetResponse(BaseModel):
    data: Optional[List[Sentence]] = None


class SentencesGetResponse(BaseModel):
    data: Optional[List[Sentence]] = None


class SentencesIdGetResponse(BaseModel):
    data: Optional[Sentence] = None
